version: '3.8'

services:
  jenkins:
    build:
      context: /opt/docker/jenkins
      dockerfile: Dockerfile
    image: jenkins-with-maven
    container_name: jenkins
    ports:
      - "127.0.0.1:8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    restart: unless-stopped
    networks:
      - jenkins_net

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: unless-stopped
    networks:
      - jenkins_net

volumes:
  jenkins_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  jenkins_net:
    driver: bridge
